site:
  title: Agentic AI 101 — Understand Agentic Workflows
  start_page: agentic-ai-101::index.adoc
content:
  sources:
    - url: .
      start_path: showroom
ui:
  bundle:
    url: https://github.com/rhpds/rhdp_showroom_theme/releases/download/patternfly-6/ui-bundle.zip
    snapshot: true
  supplemental_files: ./showroom/supplemental-ui
output:
  dir: ./showroom/build/site
