apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - runtime-deployment.yaml
  - runtime-service.yaml
  - presentation-deployment.yaml
  - presentation-service.yaml
  - presentation-route.yaml
  - network-policy.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: agentic-ai-101
      app.kubernetes.io/managed-by: launchpad
    includeSelectors: true
    includeTemplates: true
