apiVersion: v1
kind: Service
metadata:
  name: agentic-ai-101-presentation
spec:
  selector:
    app.kubernetes.io/name: agentic-ai-101
    app.kubernetes.io/component: presentation
    app.kubernetes.io/part-of: agentic-ai-101
    app.kubernetes.io/managed-by: launchpad
  ports:
    - {name: http, port: 8080, targetPort: http}
